//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiliBank.IO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IOMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IOMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiliBank.IO.IOMessages", typeof(IOMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created successfully (Account No. {0}).
        /// </summary>
        public static string AccountAddSuccess {
            get {
                return ResourceManager.GetString("AccountAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance:.
        /// </summary>
        public static string AccountBalance {
            get {
                return ResourceManager.GetString("AccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete account matching account No. {0}.
        /// </summary>
        public static string AccountDeleteFail {
            get {
                return ResourceManager.GetString("AccountDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deleted successfully.
        /// </summary>
        public static string AccountDeleteSuccess {
            get {
                return ResourceManager.GetString("AccountDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with number {0} does not exist.
        /// </summary>
        public static string AccountDoesNotExist {
            get {
                return ResourceManager.GetString("AccountDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID or account number do not exist.
        /// </summary>
        public static string AccountOrUserDoNotExist {
            get {
                return ResourceManager.GetString("AccountOrUserDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is already linked to this user.
        /// </summary>
        public static string AccountOwnedByUser {
            get {
                return ResourceManager.GetString("AccountOwnedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner ID:.
        /// </summary>
        public static string AccountOwnerId {
            get {
                return ResourceManager.GetString("AccountOwnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner name:.
        /// </summary>
        public static string AccountOwnerName {
            get {
                return ResourceManager.GetString("AccountOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP Account.
        /// </summary>
        public static string AccountVip {
            get {
                return ResourceManager.GetString("AccountVip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added user with ID {0} to account No. {1}.
        /// </summary>
        public static string AddUserToAccountSuccess {
            get {
                return ResourceManager.GetString("AddUserToAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User to an Account.
        /// </summary>
        public static string AddUserToAccountTitle {
            get {
                return ResourceManager.GetString("AddUserToAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Related Accounts.
        /// </summary>
        public static string AllAccountsByUserTitle {
            get {
                return ResourceManager.GetString("AllAccountsByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Millibank Users.
        /// </summary>
        public static string AllUsersTitle {
            get {
                return ResourceManager.GetString("AllUsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Account.
        /// </summary>
        public static string CreateAccountTitle {
            get {
                return ResourceManager.GetString("CreateAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string CreateUserTitle {
            get {
                return ResourceManager.GetString("CreateUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an Account.
        /// </summary>
        public static string DeleteAccountTitle {
            get {
                return ResourceManager.GetString("DeleteAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete user with ID: .
        /// </summary>
        public static string DeleteUserFail {
            get {
                return ResourceManager.GetString("DeleteUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully.
        /// </summary>
        public static string DeleteUserSuccess {
            get {
                return ResourceManager.GetString("DeleteUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a User.
        /// </summary>
        public static string DeleteUserTitle {
            get {
                return ResourceManager.GetString("DeleteUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deposited {0}$ to account {1}.
        /// </summary>
        public static string DepositSuccess {
            get {
                return ResourceManager.GetString("DepositSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string DepositTitle {
            get {
                return ResourceManager.GetString("DepositTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account Number.
        /// </summary>
        public static string EnterAccountNumber {
            get {
                return ResourceManager.GetString("EnterAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string GetConfirmation {
            get {
                return ResourceManager.GetString("GetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter amount.
        /// </summary>
        public static string InsertAmount {
            get {
                return ResourceManager.GetString("InsertAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user ID.
        /// </summary>
        public static string InsertId {
            get {
                return ResourceManager.GetString("InsertId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account owner&apos;s name.
        /// </summary>
        public static string InsertName {
            get {
                return ResourceManager.GetString("InsertName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the account VIP?.
        /// </summary>
        public static string InsertVipFlag {
            get {
                return ResourceManager.GetString("InsertVipFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account number.
        /// </summary>
        public static string InvalidAccountNumber {
            get {
                return ResourceManager.GetString("InvalidAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be positive and under.
        /// </summary>
        public static string InvalidAmount {
            get {
                return ResourceManager.GetString("InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option.
        /// </summary>
        public static string InvalidConfirmationInput {
            get {
                return ResourceManager.GetString("InvalidConfirmationInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID must consist of {0} digits.
        /// </summary>
        public static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid menu option.
        /// </summary>
        public static string InvalidMenuOption {
            get {
                return ResourceManager.GetString("InvalidMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must consist of {0} - {1} english characters (or white spaces).
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user to account.
        /// </summary>
        public static string MenuAddUserToAccount {
            get {
                return ResourceManager.GetString("MenuAddUserToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string MenuCreateAccount {
            get {
                return ResourceManager.GetString("MenuCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a user.
        /// </summary>
        public static string MenuCreateUser {
            get {
                return ResourceManager.GetString("MenuCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an account.
        /// </summary>
        public static string MenuDeleteAccount {
            get {
                return ResourceManager.GetString("MenuDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a user.
        /// </summary>
        public static string MenuDeleteUser {
            get {
                return ResourceManager.GetString("MenuDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string MenuDeposit {
            get {
                return ResourceManager.GetString("MenuDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print all accounts related to user.
        /// </summary>
        public static string MenuPrintAllRelatedAccounts {
            get {
                return ResourceManager.GetString("MenuPrintAllRelatedAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print all users.
        /// </summary>
        public static string MenuPrintAllUsers {
            get {
                return ResourceManager.GetString("MenuPrintAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiliBank.
        /// </summary>
        public static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string MenuWithdraw {
            get {
                return ResourceManager.GetString("MenuWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find accont matching that account number.
        /// </summary>
        public static string NoSuchAccount {
            get {
                return ResourceManager.GetString("NoSuchAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account does not have enough money to preform that action.
        /// </summary>
        public static string OverdraftNotAllowed {
            get {
                return ResourceManager.GetString("OverdraftNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        public static string PressAnyKeyToContinue {
            get {
                return ResourceManager.GetString("PressAnyKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with such ID already exists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully.
        /// </summary>
        public static string UserCreationSuccess {
            get {
                return ResourceManager.GetString("UserCreationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        public static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully withdrew {0}$ from account No. {1}.
        /// </summary>
        public static string WithdrawSuccess {
            get {
                return ResourceManager.GetString("WithdrawSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string WithdrawTitle {
            get {
                return ResourceManager.GetString("WithdrawTitle", resourceCulture);
            }
        }
    }
}
